import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'snake-ladder';
    board = [
      { pos: 10, snake: null, ladder: null },
      { pos: 9, snake: null, ladder: null },
      { pos: 8, snake: null, ladder: null },
      { pos: 7, snake: null, ladder: null },
      { pos: 6, snake: null, ladder: null },
      { pos: 5, snake: null, ladder: null },
      { pos: 4, snake: null, ladder: 14 },
      { pos: 3, snake: null, ladder: null },
      { pos: 2, snake: null, ladder: null },
      { pos: 1, snake: null, ladder: null },
      { pos: 11, snake: null, ladder: null },
      { pos: 12, snake: null, ladder: null },
      { pos: 13, snake: null, ladder: null },
      { pos: 14, snake: null, ladder: null },
      { pos: 15, snake: null, ladder: null },
      { pos: 16, snake: null, ladder: null },
      { pos: 17, snake: null, ladder: null },
      { pos: 18, snake: null, ladder: 45 },
      { pos: 19, snake: null, ladder: null },
      { pos: 20, snake: null, ladder: null },
      { pos: 30, snake: null, ladder: null },
      { pos: 29, snake: null, ladder: null },
      { pos: 28, snake: null, ladder: 84 },
      { pos: 27, snake: null, ladder: null },
      { pos: 26, snake: null, ladder: null },
      { pos: 25, snake: null, ladder: null },
      { pos: 24, snake: null, ladder: null },
      { pos: 23, snake: null, ladder: null },
      { pos: 22, snake: null, ladder: null },
      { pos: 21, snake: null, ladder: null },
      { pos: 31, snake: null, ladder: null },
      { pos: 32, snake: null, ladder: null },
      { pos: 33, snake: null, ladder: null },
      { pos: 34, snake: null, ladder: null },
      { pos: 35, snake: null, ladder: null },
      { pos: 36, snake: null, ladder: null },
      { pos: 37, snake: null, ladder: null },
      { pos: 38, snake: null, ladder: null },
      { pos: 39, snake: null, ladder: null },
      { pos: 40, snake: null, ladder: null },
      { pos: 50, snake: null, ladder: null },
      { pos: 49, snake: null, ladder: null },
      { pos: 48, snake: null, ladder: null },
      { pos: 47, snake: null, ladder: null },
      { pos: 46, snake: null, ladder: null },
      { pos: 45, snake: null, ladder: null },
      { pos: 44, snake: null, ladder: null },
      { pos: 43, snake: null, ladder: null },
      { pos: 42, snake: null, ladder: null },
      { pos: 41, snake: null, ladder: null },
      { pos: 51, snake: null, ladder: 67 },
      { pos: 52, snake: null, ladder: null },
      { pos: 53, snake: null, ladder: null },
      { pos: 54, snake: 26, ladder: null },
      { pos: 55, snake: null, ladder: null },
      { pos: 56, snake: null, ladder: null },
      { pos: 57, snake: null, ladder: null },
      { pos: 58, snake: null, ladder: null },
      { pos: 59, snake: null, ladder: null },
      { pos: 60, snake: null, ladder: null },
      { pos: 70, snake: null, ladder: null },
      { pos: 69, snake: null, ladder: null },
      { pos: 68, snake: null, ladder: null },
      { pos: 67, snake: null, ladder: null },
      { pos: 66, snake: null, ladder: null },
      { pos: 65, snake: null, ladder: null },
      { pos: 64, snake: null, ladder: null },
      { pos: 63, snake: null, ladder: null },
      { pos: 62, snake: 19, ladder: null },
      { pos: 61, snake: null, ladder: null },
      { pos: 71, snake: null, ladder: null },
      { pos: 72, snake: null, ladder: 91 },
      { pos: 73, snake: null, ladder: null },
      { pos: 74, snake: null, ladder: null },
      { pos: 75, snake: null, ladder: null },
      { pos: 76, snake: null, ladder: null },
      { pos: 77, snake: null, ladder: null },
      { pos: 78, snake: null, ladder: null },
      { pos: 79, snake: null, ladder: null },
      { pos: 80, snake: null, ladder: null },
      { pos: 90, snake: null, ladder: null },
      { pos: 89, snake: null, ladder: null },
      { pos: 88, snake: null, ladder: null },
      { pos: 87, snake: null, ladder: null },
      { pos: 86, snake: null, ladder: null },
      { pos: 85, snake: null, ladder: null },
      { pos: 84, snake: null, ladder: null },
      { pos: 83, snake: null, ladder: null },
      { pos: 82, snake: null, ladder: null },
      { pos: 81, snake: null, ladder: null },
      { pos: 91, snake: null, ladder: null },
      { pos: 92, snake: null, ladder: null },
      { pos: 93, snake: 73, ladder: null },
      { pos: 94, snake: null, ladder: null },
      { pos: 95, snake: 75, ladder: null },
      { pos: 96, snake: null, ladder: null },
      { pos: 97, snake: null, ladder: null },
      { pos: 98, snake: 7, ladder: null },
      { pos: 99, snake: null, ladder: null },
      { pos: 100, snake: null, ladder: null },
      ].reverse();
    players = [
      { name: 'Harsh', pos: 24, isActive: true },
      { name: 'Cipher', pos: 45, isActive: false },
      { name: 'Jayant', pos: 91, isActive: false },
      { name: 'Raj', pos: 9, isActive: false },
    ];
  }
